name: "Test: Ubuntu 22.04 GCC Trunk"

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3.0.2
    - name: Install
      run: |
        wget http://kayari.org/gcc-latest/gcc-latest.deb
        sudo dpkg -i gcc-latest.deb
    - name: Build
      run: LD_LIBRARY_PATH=/opt/gcc-latest/lib64 LD_RUN_PATH=/opt/gcc-latest/lib64 /opt/gcc-latest/bin/gcc sample/*.cpp test/*.cpp source/*.cpp -Iinclude -Wall -Wextra -pedantic -std=c++23 -lstdc++
    - name: Run
      run: ./a.out
