name: "Test Static Analysis: ClangTidy"

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.0
    - name: Update
      run: sudo apt update
    - name: Install
      run: sudo apt install clang-tidy-12
    - name: Tidy
      run: |
        FILES=`find . -iname *.hpp`
        clang-tidy-12 ${FILES} \
          --warnings-as-errors=* \
          -- -x c++ -Wall -Wextra -pedantic -std=c++2b -Iinclude
